### ISSUE TITLE
Compile intellij integration with Scala 2.13 for IDEA 2020.3

### ISSUE THREAD

**Issue by niktrop** [tofu-tf/derevo#184]
Since 2020.3 Scala plugin for IntelliJ IDEA will use Scala 2.13. New version of library extension compiled with Scala 2.13 should be published.

```
java.lang.NoSuchMethodError: 'scala.collection.mutable.WrappedArray scala.Predef$.wrapRefArray(java.lang.Object[])'
	at derevo.intellij.DerevoDeriveInjector$.<init>(DerevoDeriveInjector.scala:87)
	at derevo.intellij.DerevoDeriveInjector$.<clinit>(DerevoDeriveInjector.scala)
	at derevo.intellij.DerevoDeriveInjector.needsCompanionObject(DerevoDeriveInjector.scala:12)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$needsCompanion$1(SyntheticMembersInjector.scala:146)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$needsCompanion$1$adapted(SyntheticMembersInjector.scala:146)
	at scala.collection.ArrayOps$.exists$extension(ArrayOps.scala:684)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.needsCompanion(SyntheticMembersInjector.scala:146)
...
```

**Comment by tarmath** [comment]
given the plugin has been removed in https://github.com/tofu-tf/derevo/pull/240, this issue should probably be closed...
